# Generated by Django 5.2.2 on 2025-06-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='breakfast', max_length=20)),
                ('ingredients', models.TextField(max_length=500)),
                ('instructions', models.TextField(max_length=2000)),
            ],
        ),
    ]
