# Generated by Django 5.2.2 on 2025-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('snack', 'Snack'), ('appetizer', 'Appetizer')], default='breakfast', max_length=20),
        ),
    ]
