# Generated by Django 5.2.2 on 2025-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('oz', 'Ounce'), ('lb', 'Pound'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('unit', 'Whole')], max_length=10),
        ),
    ]
